profiler/profiler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'))
]

profiler/users/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login',views.loginview, name='loginview'),
    path('login/process', views.process, name='process'),
    path('logout', views.processlogout, name='processlogout'),
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('processadd', views.processadd, name='processadd'),
    path('<int:profile_id>/detail/', views.detail, name='detail'),
    path('<int:profile_id>/delete/', views.delete, name='delete'),
    path('<int:profile_id>/edit/', views.edit, name='edit'),
    path('<int:profile_id>/processedit/', views.processedit, name='processedit'),
    path('addcomment/', views.addcomment, name='addcomment'),

] + static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,
    document_root = settings.STATIC_ROOT)

profiler/users/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.utils.html import mark_safe
import os, random

now = timezone.now()
# Create your models here.

def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrst123456890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.\
        format(imageid = instance,
               basename = basefilename,
               randomstring = randomstr,
               ext = file_extension,
               year = _now.strftime('%Y'),
               month = _now.strftime('%m'),
               day = _now.strftime('%d'))

class User(models.Model):
    user_name = models.CharField(max_length=200, verbose_name='First Name')
    user_lname = models.CharField(max_length=200, verbose_name='Last Name')
    user_email = models.EmailField(unique=True, max_length=200, verbose_name='Email')
    user_position = models.CharField(max_length=200, verbose_name='Position')
    user_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')

    def image_tag(self):
        return mark_safe('<img src="/users/media/%s" width="50" height="50" />'%(self.user_image))

    pub_date = models.DateField(default=now)

    def __str__(self):
        return f'Email : {self.user_email}'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default='null')
    body = models.TextField(default='null')
    created_on = models.DateTimeField(default=now)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

profiler/users/views.py
from django.shortcuts import render,get_object_or_404, reverse
from .models import User, Comment
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect,Http404
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import login,logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
def index(request):
    user_list = User.objects.all().order_by('-id')
    paginator = Paginator(user_list, 5)

    page_number = request.GET.get('page')
    user_list = paginator.get_page(page_number)

    return render(request, 'users/index.html', {
        'page_obj': user_list,
    })

def search(request):
    term = request.GET.get('search', '')
    user_list = User.objects.filter(Q(user_name__icontains=term) | Q(user_lname__icontains=term)).order_by('-id')

    paginator = Paginator(user_list, 5)

    page_number = request.GET.get('page')
    user_list = paginator.get_page(page_number)

    return render(request, 'users/index.html', {
        'page_obj': user_list,
    })

def add(request):
    return render(request, 'users/add.html')

def processadd(request):
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    position = request.POST.get('position')

    if request.FILES.get('image'):
        user_pic = request.FILES.get('image')
    else:
        user_pic = 'profile_pic/image.jpg'

    try:
        n = User.objects.get(user_email=email)
        # number  already exists
        return render(request, 'users/add.html', {
            'error_msg': "Duplicated email: " + email
        })

    except ObjectDoesNotExist:
        user = User.objects.create(user_email=email, user_name=fname, user_lname=lname, user_position=position,
                                   user_image=user_pic)
        user.save()
        return HttpResponseRedirect('/users')

@login_required(login_url='/users/login')
def detail(request,profile_id):
        try:
            user = User.objects.get(pk=profile_id)
            comments = Comment.objects.filter(user_id=profile_id)
            comments_count = Comment.objects.filter(user_id=profile_id).count()
        except User.DoesNotExist:
            raise Http404("Profile does not exist")
        return render(request,'users/detail.html',{
                'users': user,
                'comments': comments,
                'comments_count': comments_count,
            })

def addcomment(request):
    comment_text = request.POST.get('comment')
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')

    comment = Comment.objects.create(user_id=user_id, body=comment_text, name=name, email=email)
    comment.save()
    return HttpResponseRedirect(reverse('users:detail', args=(user_id,)))

def delete(request, profile_id):
    User.objects.filter(id=profile_id).delete()
    return HttpResponseRedirect('/users')

@login_required(login_url='/users/login')
@permission_required('users.change_user', login_url='/users/login')
def edit(request, profile_id):
    try:
        user = User.objects.get(pk=profile_id)
    except User.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'users/edit.html', {
        'users': user
    })

def processedit(request, profile_id):
    user = get_object_or_404(User, pk=profile_id)
    profile_pic = request.FILES.get('image')
    try:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        position = request.POST.get('position')
    except (KeyError, User.DoesNotExist):
        return(request, 'users/details.html', {
            'user': user,
            'error_msg': "Problem updating record",
        })
    else:
        user_profile = User.objects.get(id=profile_id)
        user_profile.user_name = fname
        user_profile.user_lname = lname
        user_profile.user_email = email
        user_profile.user_position = position
        if profile_pic:
            user_profile.user_image = profile_pic
        user_profile.save()
        return HttpResponseRedirect(reverse('users:detail', args=(profile_id,)))

def loginview(request):
    return render(request, 'users/login.html')

def process(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/users')
    else:
        return render(request, 'users/login.html', {
            'error_msg': "Login Failed"
        })

def processlogout(request):
    logout(request)
    return HttpResponseRedirect('/users/login')

profiler/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>ProfilerApp | {% block title %}{% endblock %}</title>
</head>
<body>

<!--Navbar-->
{% include 'partials/_navbar.html' %}

    <div class="container">
        <div class="row mt-2">
            <div class="col-lg-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

profiler/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-dark mb-4">
    <div class="container">
        <a href="/users" class="navbar-brand">Users</a>
        <a href="/users/add" class="navbar-brand">Add New</a>
        {% if user.is_authenticated %}
            <a href="/users/logout" class="navbar-brand">Logout</a>
        {% else %}
            <a href="/users/login" class="navbar-brand">Login</a>
        {% endif %}
    </div>
</nav>

profiler/templates/users/add.html
{% extends 'base.html' %}

{% block title %}Add New User{% endblock %}

{% block content %}

{% if error_msg %}
    <p class="alert alert-danger">
        <strong>{{error_msg}}</strong>
    </p>
{% endif %}

<form action="{% url 'users:processadd' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="">First Name</label>
        <input type="text" name="fname" id="fname" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Last Name</label>
        <input type="text" name="lname" id="lname" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Email</label>
        <input type="email" name="email" id="email" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="">Position</label>
        <input type="text" name="position" id="position" class="form-control">
    </div>
    <div class="form-group mt-2">
        <label for="">User Image</label>
        <input type="file" name="image" id="image">
    </div>

    <button type="submit"class="btn btn-success mt-2">Add</button>
</form>
{% endblock %}

profiler/templates/users/detail.html
{% extends 'base.html' %}

{% block title %}{{user.user_name}} {{user.user_lname}}{% endblock %}

{% if error_msg %}
    <p class="alert alert-danger">
        <strong>{{error_msg}}</strong>
    </p>
{% endif %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="mb-5">
                <h1>{{user.user_name}} {{users.user_lname}}</h1>
                <p class="text-muted">{{users.user_email}}</p>
                <p>Position: {{users.user_position}}</p>
            </div>

            <div class="img-responsive">
                <img src="/users/media/{{users.user_image}}" alt="profile user" class="img-rounded" width="300">
            </div>

            <div class="btn-group mt-5">
                {% if user.is_staff%}
                    <a href="{% url 'users:delete' users.id %}" class="btn btn-sm btn-danger">Delete</a>
                    <a href="{% url 'users:edit' users.id %}" class="btn btn-sm btn-info">Edit</a>
                {% endif %}
                <a href="{% url 'users:index' %}" class="btn btn-sm btn-success">Return</a>
            </div>
        </div>
        <div class="col-lg-6">
            <h2>Comments</h2>
            <p class="text-muted">Total of {{comments_count}}</p>
            {% if comments_count > 0 %}
                {% for comment in comments %}
                    {% if comment.active %}
                    <p><strong>{{comment.name}}:</strong> {{comment.body}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <hr>
            <br>

            <form action="{% url 'users:addcomment' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">comment</label>
                    <textarea name="comment" id="comment" cols="30" rows="5" class="form-control" required></textarea>
                </div>

                <input type="hidden" name="user_id" id="user_id" value="{{users.id}}">
                <input type="hidden" name="name" id="name" value="{{user.username}}">
                <input type="hidden" name="email" id="email" value="{{user.email}}">

                <button type="submit" class="mt-2 btn btn-sm btn-primary">Add Comment</button>
            </form>
            <!--col-lg-6-->
        </div>
    </div>


{% endblock %}

profiler/templates/users/edit.html
{% extends 'base.html' %}

{% block title %}{{user.user_name}} {{user.user_lname}}{% endblock %}

{% block content %}

{% if error_msg %}
    <p class="alert alert-danger">
        <strong>{{error_msg}}</strong>
    </p>
{% endif %}

<form action="{% url 'users:processedit' user.id%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="">First Name</label>
        <input type="text" name="fname" id="fname" class="form-control" value="{{user.user_name}}">
    </div>
    <div class="form-group">
        <label for="">Last Name</label>
        <input type="text" name="lname" id="lname" class="form-control" value="{{user.user_lname}}">
    </div>
    <div class="form-group">
        <label for="">Email</label>
        <input type="email" name="email" id="email" class="form-control" required value="{{user.user_email}}">
    </div>
    <div class="form-group">
        <label for="">Position</label>
        <input type="text" name="position" id="position" class="form-control" value="{{user.user_position}}">
    </div>
    <div class="form-group mt-2">
        <label for="">User Image</label>
        <input type="file" name="image" id="image" value="{{user.user_name}}">
    </div>

    <button type="submit"class="btn btn-primary mt-2">Update</button>
</form>
{% endblock %}

profiler/templates/users/index.html
{% extends 'base.html' %}

{% block title %}User List{% endblock %}

{% block content %}
  <form action="{% url 'users:search' %}" method='GET' class="mb-4 mt-2">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search" name="search" required>
      <div class="input-group-append">
        <button type="submit" class="btn btn-success">Search</button>
      </div>
    </div>
  </form>
  <h1 class="text-center mb-4">Profiler App</h1>

  {% if page_obj %}
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th class="text-center">Profile Image</th>
        </tr>
      </thead>
      <tbody>
        {% for user in page_obj %}
        <tr>
          <td>{{user.user_name}}</td>
          <td>{{user.user_lname}}</td>
          <td>{{user.user_email}}</td>
          <td class="text-center">
            <a href="{% url 'users:detail' user.id %}">
              <img src="media/{{user.user_image}}" alt="userimage" width="50" class="rounded-circle">
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page=1" class="page-link">&laquo;  First</a></li>
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> previous</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{page_obj.next_page_number}}" class="page-link">  next</a></li>
            <li class="page-item"><a href="page_obj.paginator.num_pages" class="page-link">&raquo; last</a></li>
        {% endif %}
    </ul>


  </div>
  {% else %}
    <p>no record</p>
  {% endif %}

{% endblock %}

profiler/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-6 m-auto">
        {% if error_msg %}
          <p class="alert alert-danger">
            <strong>{{error_msg}}</strong>
          </p>
        {% endif %}

          <div class="text-center">
            <h2>Login Form</h2>
          </div>

          <form action="{% url 'users:process' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
              <label>Username</label>
              <input type="text" name="username" id="username" class="form-control" placeholder="Enter Username"
                     autocomplete="off">
            </div>

            <div class="form-group">
              <label>Password</label>
              <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password">
            </div>

            <button type="submit" class="btn btn-success">Login</button>
          </form>
      </div>
    </div>
  </div>
{% endblock %}